modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL="https://github.com/BigVirusBoi/Bobs-Food-Mod/issues"

[[mods]]
modId = "bobs_food_mod"
version = "${file.jarVersion}"
displayName = "Bob's Food Mod"
#updateJSONURL=""
#displayURL=""
logoFile="logo.png"
authors = "BigVirusBoi"
description = '''This mod adds new food'''

[[dependencies.bobs_food_mod]]
modId="forge"
mandatory=true
versionRange="[36.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.bobs_food_mod]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
